version: '3.8'

services:
  inference-api:
    build:
      context: ./inference-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./inference-api:/app
    environment:
      - MODEL1_PATH=/app/models/model1.onnx
      - MODEL2_PATH=/app/models/model2.onnx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
